# Site settings
title: "Stormwild"
email: artorrijos@gmail.com
site.description: "Stormwild (Alexander R. Torrijos)"
url: "http://stormwild.github.io"

# Build settings
permalink: pretty

#exclude:
#  - "bower_components"

# Environment settings
timezone: Asia/Manila
encoding: utf-8

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      author: "Alexander R. Torrijos"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default" # overrides previous default layout
      author: "Alexander R. Torrijos"
