# Site settings
title: "Stormwild (Alexander R. Torrijos)"
email: artorrijos@gmail.com
description: "Stormwild (Alexander R. Torrijos)"
url: "http://stormwild.github.io"

# Build settings
permalink: pretty

paginate: 20
paginate_path: "/blog/page:num/"


#exclude:
#  - "bower_components"

# Environment settings
timezone: Asia/Manila
encoding: utf-8

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      author: "Alexander R. Torrijos"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "blog" # overrides previous default layout
      author: "Alexander R. Torrijos"
  -
    scope:
      path: "_pages"
      type: "pages"      
    values:
      type: "page"
include: ["_pages"]
plugins_dir: [jekyll-sitemap, jekyll-redirect-from, jekyll-paginate, jekyll-gist]
whitelist:
  - jekyll-redirect-from  
github: [metadata]